server:
  port: 8080
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/pidms?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 375862190
    driver-class-name: com.mysql.jdbc.Driver
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: bst
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1s
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true
  mapper-locations: classpath*:/mapper/**Mapper.xml
jodconverter:
  local:
    enabled: true
    office-home: "C:\\Program Files (x86)\\OpenOffice 4"
    max-tasks-per-process: 100
    port-numbers: 8100
logging:
  file: pidms.log
  config: classpath:logging-spring.xml